# Generated by Django 3.2.4 on 2021-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
